### ISSUE TITLE
Segmentation violation in edi2edi

### ISSUE THREAD

**Issue by petrn** [digris/digris-edi-zmq-bridge#6]
The following command running on Rpi5 under Debian 12

`digris-edi2edi -w 1000 -v -i 0 -p 12345 -d 239.255.10.10 -s 13000 -S 127.0.0.1 -t 2 -c 172.30.31.149:9201`

ends in a few seconds in segmentation violation. The EDI tcp stream comes from odr-dabmux over TCP.

```
DIGRIS-EDI2EDI v0.6.0 starting up
Developed for Opendigitalradio by digris: https://www.digris.ch

2024-12-20Z10:43:19       Setting up EDI2EDI with delay 1000 ms.
2024-12-20Z10:43:19       EDI inputs
2024-12-20Z10:43:19        172.30.31.149:9201 enabled
2024-12-20Z10:43:19       EDI Output
2024-12-20Z10:43:19        verbose     0
2024-12-20Z10:43:19        UDP to 239.255.10.10:12345
2024-12-20Z10:43:19         source      127.0.0.1
2024-12-20Z10:43:19         ttl         2
2024-12-20Z10:43:19         source port 13000
2024-12-20Z10:43:19       ZMQ output: disabled
2024-12-20Z10:43:19       Connection to 172.30.31.149:9201 reestablished
2024-12-20Z10:43:19       Initialise next_pseq to 11000
2024-12-20Z10:43:19       pseq 11000 timed out
2024-12-20Z10:43:19       pseq 11001 timed out
2024-12-20Z10:43:20       pseq 11002 timed out
2024-12-20Z10:43:20       EDI AF Packet initial sequence number: 11003
Segmentation fault
```

Under gdb, the crash happens like this:

```
#0  __memcpy_generic () at ../sysdeps/aarch64/multiarch/../memcpy.S:161
#1  0x0000555555565208 in std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<unsigned char> (__result=<optimized out>, __last=<optimized out>, __first=<optimized out>)
    at /usr/include/c++/12/bits/stl_algobase.h:431
#2  std::__copy_move_a2<false, unsigned char*, unsigned char*> (__result=<optimized out>, __last=<optimized out>, __first=<optimized out>) at /usr/include/c++/12/bits/stl_algobase.h:495
#3  std::__copy_move_a1<false, unsigned char*, unsigned char*> (__result=<optimized out>, __last=<optimized out>, __first=<optimized out>) at /usr/include/c++/12/bits/stl_algobase.h:522
#4  std::__copy_move_a<false, __gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, __gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > > > (__result=..., __last=..., __first=...) at /usr/include/c++/12/bits/stl_algobase.h:529
#5  std::copy<__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, __gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > > > (__result=..., __last=..., __first=...) at /usr/include/c++/12/bits/stl_algobase.h:620
#6  EDISender::send_tagpacket (this=this@entry=0x7fffffff8f00, tp=...) at src/EDISender.cpp:276
#7  0x0000555555566418 in EDISender::process (this=0x7fffffff8f00) at src/EDISender.cpp:323
#8  0x00007ffff7d7e9dc in ?? () from /lib/aarch64-linux-gnu/libstdc++.so.6
#9  0x00007ffff7a8ee90 in start_thread (arg=0x7fffffff88b7) at ./nptl/pthread_create.c:442
#10 0x00007ffff7af7b1c in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:79
```

**Comment by YoannQueret** [comment]
Can you try with next version ? I can't reproduce with v0.6.0-8-gdbc6d91

**Comment by petrn** [comment]
Thanks, the version in the "next" branch seems to work fine.

```
DIGRIS-EDI2EDI v0.6.0-22-g1633de3 starting up
Developed for Opendigitalradio by digris: https://www.digris.ch

2024-12-20Z16:53:24       Setting up EDI2EDI with delay 1000 ms.
2024-12-20Z16:53:24       EDI inputs
2024-12-20Z16:53:24        172.30.31.149:9201 enabled
2024-12-20Z16:53:24       EDI Output
2024-12-20Z16:53:24        verbose     0
2024-12-20Z16:53:24        PFT         1
2024-12-20Z16:53:24        UDP to 239.255.10.10:12345
2024-12-20Z16:53:24         source      192.168.112.149
2024-12-20Z16:53:24         ttl         2
2024-12-20Z16:53:24         source port 13000
2024-12-20Z16:53:24       ZMQ output: disabled
2024-12-20Z16:53:24       Connection to 172.30.31.149:9201 reestablished
2024-12-20Z16:53:24       Initialise next_pseq to 18715
2024-12-20Z16:53:24       EDI AF Packet initial sequence number: 18715
```

**Comment by mpbraendli** [comment]
Thanks for letting us know, I'll consider this fixed.
